### ISSUE TITLE
vsgFramework is actually broken

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgFramework#12] opened 2023-01-18 08:19 UTC
When building the vsg ecosystem an error occurs with vsgImgui:

**[7/9] No install step for 'vsgimgui-populate'
[8/9] No test step for 'vsgimgui-populate'
[9/9] Completed 'vsgimgui-populate'
CMake Error at /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/cmake/vsgImGuiMacros.cmake:13 (file):
  file COPY cannot find
  "/Users/rainerge/Documents/GitHub/vsgFramework/src/imgui/imgui.h": No such
  file or directory.
Call Stack (most recent call first):
  /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/CMakeLists.txt:42 (vsg_copy_imgui_headers)

copied imgui.h
CMake Error at /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/cmake/vsgImGuiMacros.cmake:13 (file):
  file COPY cannot find
  "/Users/rainerge/Documents/GitHub/vsgFramework/src/imgui/imconfig.h": No
  such file or directory.
Call Stack (most recent call first):
  /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/CMakeLists.txt:42 (vsg_copy_imgui_headers)

copied imconfig.h
CMake Error at /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/cmake/vsgImGuiMacros.cmake:13 (file):
  file COPY cannot find
  "/Users/rainerge/Documents/GitHub/vsgFramework/src/imgui/imgui_internal.h":
  No such file or directory.
Call Stack (most recent call first):
  /Users/rainerge/Soft/Entwicklung/VSG3/build/components/vsgimgui-src/CMakeLists.txt:42 (vsg_copy_imgui_headers)**

This happens on MacOS and on Windows.

**Comment by robertosfield** [comment] 2023-01-18 10:29
I haven't had a chance to look at the issue, but from the above messages it looks like the paths used to copy across the imgui headers don't handle use as sub project.  Feels familiar to problems we've had to resolve before by changing the project path used.

**Comment by rserban** [comment] 2023-01-18 13:29
@robertosfield, that's correct. Looks like this was caused by the vsgImGui commit #bfe3658.  The issue appears to have been resolved with a recent commit.

**Comment by rserban** [comment] 2023-01-18 16:45
Turns out there's a new bug related to vsgImGui that shows up when building vsgFramework: `imconfig.h` not found.  The header exists, but under `compnents/vsgimgui-src/src/` and that directory is not added to the includes.  Also, `imconfig.h` is not being installed.

**Comment by rserban** [comment] 2023-01-28 08:27
> Turns out there's a new bug related to vsgImGui that shows up when building vsgFramework: `imconfig.h` not found. The header exists, but under `compnents/vsgimgui-src/src/` and that directory is not added to the includes. Also, `imconfig.h` is not being installed.

Any comments or suggestions about this? I also posted this as an issue on the vsg_imgui project - bu no response there either...

**Comment by robertosfield** [comment] 2023-01-28 08:33
Personally have a range of tasks to get on with and can't follow up an all
issues right away. This issue will need to be investigated, but I can't
tackle it right away.

**Comment by rserban** [comment] 2023-01-29 10:58
Fair enough, Robert.  Thanks for the reply!

**Comment by robertosfield** [comment] 2023-01-30 11:20
Finally got to investigating this issue.  I was able to reproduce the issue on my system, and after the following change to vsgImGui I now get a clean build:

https://github.com/vsg-dev/vsgImGui/pull/43

**Closed as completed by robertosfield** 2023-01-30 11:20 UTC
